# IATA 항공사 코드 목록
# 전 세계 항공사의 공식 IATA 코드들

AIRLINE_CODES = [
    "KE", "OZ", "7C", "LJ", "BX", "ZE", "TW", "RS", "YP", "RF", "KJ", "2I", "Q5",
    "FE", "AQ", "Y6", "GB", "K4", "YJ", "GP", "3V", "5O", "PH", "4A", "CJ", "A0",
    "B5", "8H", "H5", "2C", "OK", "DX", "L3", "ES", "D0", "Q7", "D5", "7T", "LI",
    "8D", "C0", "9A", "IV", "A5", "II", "AZ", "XE", "FK", "KL", "WA", "KK", "LV",
    "GE", "LO", "WW", "7M", "M2", "OM", "MB", "6V", "MU", "2P", "PB", "CG", "OH",
    "S7", "RZ", "5S", "SK", "SL", "SP", "O3", "KI", "S0", "8F", "DT", "T0", "TP",
    "TP", "YQ", "RO", "X3", "OR", "6B", "TB", "BY", "GO", "5X", "UD", "BS", "UJ",
    "RT", "V6", "2Z", "YG", "GA", "GT", "G2", "IF", "GF", "GW", "G8", "JS", "G7",
    "6G", "G3", "Y5", "G1", "5U", "GX", "CN", "YR", "GV", "HB", "Q9", "Z5", "G6",
    "5S", "GE", "ON", "NP", "NJ", "T2", "NM", "IN", "SA", "N8", "9Y", "NA", "NE",
    "NO", "RA", "1I", "NC", "Y7", "N4", "ND", "N7", "Z0", "N0", "DY", "DY", "D8",
    "NA", "O9", "NG", "VQ", "0N", "HW", "J3", "DD", "N5", "BJ", "EJ", "7H", "OJ",
    "9J", "DN", "D3", "DL", "R6", "ZQ", "DZ", "KB", "3R", "4Y", "DF", "LC", "B0",
    "R4", "TH", "LK", "QV", "LW", "7S", "FR", "RK", "JT", "8V", "M3", "UC", "L7",
    "LA", "JJ", "XL", "LA", "4C", "PZ", "LP", "LQ", "TM", "P7", "BN", "8L", "WZ",
    "L5", "7H", "QL", "R0", "LC", "ZL", "LM", "FV", "AT", "BI", "RW", "RJ", "3Q",
    "RG", "L8", "L9", "7R", "5R", "LH", "CL", "LH", "VL", "LG", "NJ", "GJ", "LT",
    "WB", "YL", "LN", "5U", "4P", "EX", "8N", "F2", "YX", "L2", "L0", "RI", "FC",
    "UJ", "DI", "O8", "MP", "4M", "M7", "MY", "2M", "2Y", "N7", "C6", "LL", "5G",
    "MJ", "9T", "W5", "6M", "AE", "7Y", "NR", "3W", "DB", "MH", "VM", "DJ", "4X", 
    "N5", "BM", "YV", "WD", "L6", "Q2", "MT", "XF", "ME", "M4", "UB", "8M", "K7", 
    "J4", "OD", "ID", "UP", "PG", "V9", "VK", "QH", "NB", "2T", "J8", "RR", "VS", 
    "VA", "XR", "BD", "J0", "8E", "CH", "3B", "JV", "JD", "VN", "0V", "V4", "B2", 
    "AB", "VI", "N3", "Q6", "Y4", "V7", "OB", "2L", "U4", "RP", "UZ", "VY", "B3", 
    "4B", "LB", "FB", "TF", "NT", "TT", "1X", "SN", "MX", "SI", "BV", "BZ", "BO", 
    "BZ", "BG", "VB", "BH", "UK", "V4", "VJ", "VU", "B4", "UQ", "NT", "VP", "OL", 
    "OL", "SV", "S1", "WN", "2S", "9R", "F2", "ZF", "FA", "SC", "OV", "SO", "FM", 
    "MF", "SH", "CE", "IH", "9X", "PL", "SY", "R8", "SR", "2U", "S6", "2R", "YH", 
    "EZ", "WG", "ZH", "DK", "ER", "D2", "5J", "DG", "C2", "K3", "PV", "IS", "9M", 
    "5Z", "SZ", "6J", "FW", "IE", "SP", "SK", "DR", "SD", "SJ", "PY", "Y8", "N9", 
    "IU", "UL", "5N", "6Y", "2N", "QS", "6D", "3Z", "7O", "2E", "LX", "WT", "Y3", 
    "ML", "3E", "BQ", "ZA", "GQ", "H2", "RD", "H8", "UY", "S8", "U3", "QU", "GG", 
    "BC", "PQ", "U5", "OW", "OO", "LC", "M8", "TE", "QN", "DO", "DV", "TR", "HK", 
    "S5", "2I", "JX", "4E", "4R", "7G", "SG", "SG", "P8", "NK", "C7", "YR", "5G", 
    "RB", "BB", "SI", "A2", "QG", "WX", "K5", "3M", "US", "7L", "ZP", "7E", "SQ", 
    "SQ", "XQ", "3U", "XO", "EH", "DM", "AG", "6A", "JI", "AR", "FG", "W3", "Z8", 
    "MZ", "A8", "M6", "AA", "8R", "XP", "YK", "4B", "ZR", "GU", "A0", "2K", "TA", 
    "WC", "QT", "LR", "AV", "9V", "X9", "X8", "JU", "4K", "KP", "0A", "8V", "P9", 
    "KP", "GM", "AM", "6R", "5D", "E4", "SU", "FW", "FI", "Q7", "F7", "2O", "I4", 
    "J2", "S4", "ZF", "AD", "2F", "AJ", "QP", "AK", "V8", "5Y", "RC", "J7", "AW", 
    "XU", "BU", "8U", "6L", "O4", "KO", "J5", "AS", "JN", "G4", "DQ", "6R", "KH", 
    "VC", "QQ", "UJ", "AP", "2B", "G0", "5A", "2G", "Q3", "A2", "IZ", "YE", "YC", 
    "R3", "AN", "4W", "9I", "UE", "A3", "WK", "B8", "EA", "ET", "EK", "BR", "8K", 
    "5V", "GD", "ES", "GT", "GL", "4N", "PX", "NZ", "EN", "HD", "RM", "GZ", "7I", 
    "LZ", "ZM", "MD", "NX", "KM", "MV", "MK", "4O", "NF", "KF", "BP", "2J", "C7", 
    "PJ", "HC", "JU", "HM", "Y2", "GI", "PF", "G9", "3O", "3L", "E5", "KC", "2A", 
    "NY", "ZB", "6I", "AH", "TZ", "CC", "UU", "3N", "N6", "ZW", "X5", "UX", "3H", 
    "AI", "IX", "9H", "CA", "CA", "DJ", "UM", "3C", "3E", "2Q", "TX", "TY", "AC", 
    "RV", "AC", "KS", "XK", "HF", "YN", "IK", "VT", "TN", "ST", "TC", "TS", "A6", 
    "8C", "6C", "8T", "7P", "FS", "AF", "F4", "P4", "HT", "LD", "AO", "TL", "KA", 
    "8G", "N2", "NL", "3S", "M0", "V5", "KW", "2S", "7L", "F5", "ZV", "XZ", "K2", 
    "EI", "EI", "4Z", "X8", "BT", "4Y", "RU", "PA", "T6", "AK", "D7", "ED", "NQ", 
    "JK", "EF", "SM", "SB", "P2", "RE", "ZD", "VF", "8J", "ZU", "ET", "EY", "EE", 
    "9E", "MQ", "E4", "G4", "7Q", "EL", "LY", "BS", "BA", "IY", "YT", "O7", "HZ", 
    "6O", "GR", "OC", "OG", "UI", "WY", "OF", "OS", "YI", "BK", "OA", "OY", "EB", 
    "WP", "Q9", "R5", "UR", "U6", "UQ", "HY", "PS", "4W", "OX", "WL", "3G", "2W", 
    "3P", "KD", "WU", "PN", "WS", "WR", "WC", "WF", "W6", "W4", "5W", "W9", "7W", 
    "WH", "P5", "IW", "UA", "B7", "U7", "6U", "QY", "H6", "PS", "YU", "Q4", "E6", 
    "EW", "YZ", "UF", "UT", "RF", "X7", "H7", "IA", "EP", "B9", "IR", "IO", "E9", 
    "I2", "YW", "IB", "QI", "E7", "T3", "I8", "MG", "RD", "7Z", "U2", "DS", "EC", 
    "MS", "EO", "E7", "XN", "7A", "QE", "QZ", "6E", "I7", "JY", "I4", "8B", "V8", 
    "IJ", "JL", "JC", "KZ", "JO", "J9", "JM", "ZN", "RY", "JG", "QK", "NU", "LC", 
    "NH", "JL", "ZK", "B6", "WJ", "JA", "JZ", "3K", "GK", "JQ", "4J", "LS", "JO", 
    "JR", "A9", "GH", "6J", "3J", "IM", "HO", "CZ", "CZ", "CO", "MU", "G5", "I9", 
    "CK", "CI", "XM", "D4", "ZG", "9D", "TZ", "KN", "CF", "VC", "6Q", "X7", "5C", 
    "GS", "HT", "EU", "GM", "9C", "OQ", "QW", "C3", "6L", "CV", "C8", "W8", "PM", 
    "HH", "8F", "NV", "V3", "BW", "QC", "Z7", "9Q", "IQ", "QR", "VR", "A7", "K4", 
    "K9", "MO", "RQ", "K6", "KR", "5T", "AU", "CX", "C5", "6C", "LF", "GY", "HQ", 
    "KQ", "QB", "8K", "KX", "9K", "M5", "4K", "CD", "XC", "XR", "SS", "KO", "GW", 
    "CQ", "7C", "CM", "P5", "FC", "DE", "V0", "C4", "8Z", "QF", "CU", "KU", "KY", 
    "QO", "QA", "KV", "C8", "OU", "VE", "KG", "FK", "Z3", "TB", "3T", "SF", "SL", 
    "VZ", "FD", "XJ", "TG", "IT", "ZT", "TM", "HJ", "K3", "TK", "TI", "TQ", "BV", 
    "T5", "T9", "U8", "TU", "UG", "M8", "T7", "8B", "HV", "TO", "R2", "Q8", "T7", 
    "C3", "TJ", "9N", "IL", "TD", "T7", "TV", "5P", "ZP", "P6", "FY", "PK", "HP", 
    "OP", "8Y", "P1", "8P", "BL", "PC", "7V", "FX", "FN", "UF", "DP", "PD", "NI", 
    "PO", "PI", "Z4", "FU", "6P", "BF", "P0", "F9", "FS", "FA", "4F", "E3", "3X", 
    "MI", "FH", "P6", "PW", "SX", "WV", "XY", "FL", "5M", "IF", "S9", "G6", "EQ", 
    "8W", "F0", "5F", "FT", "9P", "FP", "FZ", "FO", "FA", "F3", "3F", "F6", "YS", 
    "D3", "PU", "F8", "OG", "W2", "PT", "FJ", "MM", "PE", "AY", "HI", "Z2", "PR", 
    "YB", "HA", "5K", "3L", "HU", "HG", "H4", "H7", "HR", "NS", "HN", "H3", "H3", 
    "JB", "2L", "QX", "5Q", "HD", "UO", "HX", "RH", "RS", "WI", "JH", "MR", "HJ", 
    "H9", "OI",

    "HL" # 학습데이터에 있는 가짜 항공편 코드
]

def is_valid_airline_code(code: str) -> bool:
    """주어진 코드가 유효한 항공사 IATA 코드인지 확인"""
    return code.upper() in AIRLINE_CODES

def get_flight_code_pattern(code: str) -> str:
    """항공사 코드에 대한 정규식 패턴 반환"""
    return rf'\b({code}\d{{1,4}})\b'