spring.application.name=back
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=chatbot

# Actuator
management.endpoints.web.exposure.include=health,info,mappings

# OpenAI
openai.api.key=${OPENAI_API_KEY}

# API
flight.api.url=https://api.airport.kr/flight
flight.api.key=${FLIGHT_API_KEY}

management.endpoint.health.show-details=always
